name: 03 Basics Events Filters

on:
#  pull_request:
#    types:
#      - closed
  push:
#    branches:
#      - main
#    branches-ignore:
#      - main
#    tags:
#      - v2
#    tags-ignore:
#      - v1
    paths:
      - "routes/wen.php"
      - "routes/*.php"
      - "routes/**.php"

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
